### PR TITLE
Update ClojureScript to 1.9.521 (same as duct/server.figwheel)

### PR DESCRIPTION
**Pull request by scottlowe**
I ran `lein test` with no issues 👌

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you remove the "Exclude IntelliJ" commit from the PR?

**Comment by scottlowe** [comment]
I've removed the `.gitignore` commit, as requested. Does that mean that you'd prefer not to receive future additions to `.gitignore`, or are you simply indicating that you prefer a strict separation of concerns in PRs?

**Comment by weavejester** [comment]
Both reasons 😃 

I think IDE-specific ignore directives are probably better suited to project-local ignore files, such as `.git/info/ignore` in the project directory, or user-local ignore files, such as the one defined by the `core.excludesfile` option.

So one thing I've done is to create a global .gitignore:

    git config --global core.excludesfile ~/.gitignore_global

And then I've added all my IDE-specific ignore patterns to that.

**Comment by scottlowe** [comment]
Okay, thanks for the explanation (and education)! I was asking because the project I'm currently working on uses the duct-framework, so I may submit PRs for other modules in the future, and it's good to know what you want, what you expect and how you work 😄

**Comment by weavejester** [comment]
Are you using the alpha version?

**Comment by scottlowe** [comment]
Currently have the following dependencies:

    [duct/core "0.1.1"]
    [duct/module.logging "0.1.1"]
    [duct/module.web "0.1.1"]
    [duct/module.cljs "0.1.2"]

Project is fairly bare-bones at the moment, and we appreciate that it's early days for *duct*. 

Background: We've started a new project and a significant requirement was that we wanted to use *integrant*, rather than *component* or *mount*, since we've not been satisfied with either of those in other projects.

**Comment by weavejester** [comment]
There shouldn't be *too* many significant changes in the future, but I have just released two breaking changes for 0.9.0-alpha3 that are probably worth mentioning.

The first is that from Integrant 0.4.0 onward, `#ref` has been changed to `#ig/ref`. See weavejester/integrant#12 for the discussion around that.

The second is that Duct modules from version 0.2.0 onward are self-ordering, so they no longer require the `:duct.core/modules` key. See the [modules](https://github.com/duct-framework/core#modules) section of the duct/core project.

If you have any feedback around the Duct 0.9.0 alpha, I'd be interested to hear it.

**Comment by scottlowe** [comment]
Cheers. Much appreciated. Will update the project now.

Hey, are you *actually* in the UK right now? It's well after 2am there!

**Comment by weavejester** [comment]
It is, but I like working late :)

**Pull request merged**
